
["Botany Pots Tiers Options"]
	#
	#Creative Botany Pot Speed
	#Range: > 1
	creativeBotanyPotSpeed = 600
	#
	#Ultra Botany Pot Speed
	#Range: > 1
	ultraBotanyPotSpeed = 10
	#
	#Ultra Botany Pot Multiplier
	#Range: > 1
	ultraBotanyPotMultiplier = 10
	#
	#Elite Botany Pot Speed
	#Range: > 1
	eliteBotanyPotSpeed = 4
	#
	#Elite Botany Pot Multiplier
	#Range: > 1
	eliteBotanyPotMultiplier = 4
	#
	#Creative Botany Pot Multiplier
	#Range: > 1
	creativeBotanyPotMultiplier = 600

